### ISSUE TITLE
Subset catalog by tag

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-datastore-flask#11]
Currently, most of the data in Pangeo's catalog is in the same cloud region. I expect that, in the future, we'll move to a more distributed storage system where we may want to point to data on multiple clouds/regions. For this reason, it will be convenient to subset data by cloud vendor and region. Perhaps something like this would work:

```yaml
  cgiar_pet:
    ...
    metadata:
      ...
      tags:
        - ...
        - location: gcp-us-central1  
    driver: zarr
    args:
      ...
```

Another option would be to rework the catalog nesting to represent this level of per-cloud structure.

On the flask-app side, I think it would be useful to understand what is possible in terms of subsetting and how we can leverage intake search capabilities to make this possible.
